export { WelcomeBlock } from './welcome-block'
export { RegisterFormStepOne } from './register/register-form-step-one'
export { RegisterFormStepTwo } from './register/register-form-step-two'
export { LoginForm } from './login'
export { FooterBlock } from './footer-block'